const projects = [
  {
    title: 'TWHelp',
    description:
      'A stat tracking and tools website, scripts, a public GraphQL API and a Discord bot for the browser-based game Tribal Wars.',
    technologies: [
      'GraphQL',
      'Golang',
      'gqlgen',
      'Gin',
      'bwmarrin/discordgo',
      'robfig/cron',
      'Redis',
      'PostgreSQL',
      'TypeScript',
      'React',
      'Gatsby',
      'Material-UI',
      'Create React App',
      'Apollo',
      'Parcel',
      'Docker',
      'Traefik',
    ],
    github: 'https://github.com/tribalwarshelp',
    fluid: 'projects/twhelp.png',
    live: 'https://tribalwarshelp.com/',
  },
  {
    title: 'Zdam Egzamin Zawodowy',
    description:
      'A mobile and web app for practising the theoretical part of the vocational exam.',
    technologies: [
      'GraphQL',
      'Golang',
      'gqlgen',
      'go-chi',
      'PostgreSQL',
      'TypeScript',
      'React',
      'React Native',
      'Next.JS',
      'Create React App',
      'Material-UI',
      'Apollo',
      'Traefik'
    ],
    fluid: 'projects/zdam.png',
    live: 'https://zdamegzaminzawodowy.pl/',
    github: 'https://github.com/zdam-egzamin-zawodowy',
  },
  {
    title: 'dwysokinski.me',
    description: '',
    technologies: ['React', 'Gatsby', 'Material-UI'],
    github: 'https://github.com/Kichiyaki/dwysokinski.me',
    live: 'https://dwysokinski.me',
    fluid: 'projects/dw.png',
  },
  {
    title: 'OLX Crawler',
    description: 'An app written in Go to observe olx.pl ads.',
    technologies: [
      'Golang',
      'Colly',
      'SQLite3',
      'Echo',
      'React',
      'Material-UI',
    ],
    fluid: 'projects/olx.png',
    github: 'https://github.com/Kichiyaki/olx-crawler',
  },
  {
    title: 'Instaling.pl Bot',
    description: 'A bot that solves the instaling.pl vocabulary tests for you.',
    technologies: ['Golang', 'Lorca'],
    fluid: 'projects/instaling.png',
    github: 'https://github.com/Kichiyaki/Instaling-Bot',
  },
  {
    title: 'Margonem Mini Bot',
    description: 'A bot for the mobile client of the MMORPG game Margonem.',
    technologies: ['Golang', 'Colly'],
    fluid: 'projects/margonem.png',
    github: 'https://github.com/Kichiyaki/margonem-mini-bot',
  },
  {
    title: 'Akademia Młodego Inżyniera',
    description: '',
    technologies: ['HTML', 'CSS', 'Bootstrap'],
    live: 'https://dwysokinski.me/preview/akademia/',
    fluid: 'projects/amz.png',
  },
  {
    title: 'Freshline',
    description: '',
    technologies: ['Wordpress', 'CSS', 'Bootstrap'],
    live: 'http://fresh-line.pl/',
    fluid: 'projects/freshline.png',
  },
];

export default projects;
